/* Exporting the components to be used in the routes.*/
export {default as Jobs} from '../pages/Public_View/Jobs/Jobs';
export {default as Posts} from '../pages/Public_View/Posts/Posts';
export {default as Post} from '../pages/Public_View/Posts/Post';
export {default as Faqs} from '../pages/Public_View/Profile/Faqs';
export {default as Tips} from '../pages/Public_View/Tips/Tips';
export {default as Error404} from '../pages/Shared_View/Error_404/Error404';
export {default as Home } from '../pages/Shared_View/HomeVisitors/HomeVisitors';
export {default as HomeAdmins} from '../pages/Shared_View/Home/HomeAdmin';
export {default as Login} from '../pages/Shared_View/Login/Login';
export {default as Register} from '../pages/Shared_View/Register/Register';
export {default as RecoverPassword} from '../pages/Shared_View/Recover_Password/RecoverPassword';
export {default as CmsBlog} from '../pages/User_View/CMS_blog/CmsBlog';
export {default as CmsEmployments} from '../pages/User_View/CMS_employments/CmsEmployments';
export {default as CmsFaqs} from '../pages/User_View/CMS_faqs/CmsFaqs';
export {default as CmsTips} from '../pages/User_View/CMS_tips/CmsTips';
export {default as CmsUsers} from '../pages/User_View/CMS_Users/CmsUsers';
export {default as Interview} from '../pages/User_View/Interview/Interview';
export {default as PantallaChat} from '../pages/User_View/Chat/PantallaChat';
export {default as Resume} from '../pages/User_View/Resume/Resume';
export {default as Profile} from '../pages/User_View/Profile/Profile';